export const storeProducts = [
  {
    id: 1,
    title: "70th Anniversary Esquire",
    img: "img/product01.jpg",
    price: 3999.0,
    company: "Fender",
    info:
      "The very first solid-body electric guitar offered by Fender in 1950 was the Esquire. With an elegant single-cutaway silhouette, adjustable 3-saddle bridge and a lone, repurposed lap-steel pickup in the bridge position – the Esquire laid the groundwork for all solidbody electric guitars to follow and foreshadowed its more famous sibling, the Telecaster.Like the earliest Esquire models, the 70th Anniversary Esquire features a pine body – a lightweight wood known for punchy and complex tone – and upgrades it with our roasting treatment, greatly improving the resonance of the body. Other features include a lacquer finish, thick “U”-shaped neck, Tim Shaw-designed Esquire bridge pickup – inspired by an original ’50 Esquire from Songbirds Museum in Chattanooga, TN - special anniversary neck plate and tweed case.Production of the 70th Anniversary Esquire will be limited to 2020 only.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Brent Mason Telecaster",
    img: "img/product02.jpg",
    price: 4999.0,
    company: "Fender",
    info:
      "With recording credits stretching across five decades, Brent Mason is one of the most prolific session guitarists of all time, featured on well over 1,000 albums, including hits by Alan Jackson, Brooks & Dunn, George Jones, Dolly Parton, Blake Shelton, Shania Twain and many more. He’s also been inducted into the Musicians Hall of Fame, won a Grammy, earned twelve Guitarist of the Year awards from the Academy of Country Music, is a two-time winner of the CMA® Award Musician of the Year Award and was named one of the top ten session guitarists of all time by Guitar World magazine.The Stories Collection Brent Mason Telecaster recreates the prized Tele he discovered in a Nashville guitar shop in the early eighties: a ‘67 model that had been stripped of its original finish and re-sprayed in gray auto primer. Brent outfitted it with new pickups and controls, as well as a bender system – transforming it into a versatile all-in-one session guitar.Boasting a Glaser Bender system, Seymour Duncan mini-hum in the neck position, Hot Stack in the middle and Vintage Stack in the bridge, locking Sperzel tuners and Dunlop locking strap buttons – the Brent Mason Telecaster provides the special features, smooth playability and diverse range of tones to nail Brent’s platinum Nashville session sound.Includes deluxe hardshell case.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Shawn Mendes Foundation",
    img: "img/product03.jpg",
    price: 1499.0,
    company: "Fender",
    info:
      "The Shawn Mendes Foundation Musicmaster is a unique combination of exquisite vintage art and classic Fender tone. Adorned with a fan's rendition of a striking floral design, this highly personal take on the popular 60s short-scale model features an alder body, “C”-shaped maple neck with 9.5” radius, 22 medium jumbo frets and a unique single/hum pickup configuration, providing a wide range of Fender tones.This collaboration is made possible through Fender's charitable support of the Shawn Mendes Foundation.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "American Ultra Telecaster",
    img: "img/product04.jpg",
    price: 3899.0,
    company: "Fender",
    info:
      "American Ultra is our most advanced series of guitars and basses for discerning players who demand the ultimate in precision, performance and tone. The American Ultra Telecaster features a unique “Modern D” neck profile with Ultra rolled fingerboard edges for hours of playing comfort, and the tapered neck heel allows easy access to the highest register. A speedy 10”-14” compound-radius fingerboard with 22 medium-jumbo frets means effortless and accurate soloing, while the Ultra Noiseless™ Vintage pickups and advanced wiring options provide endless tonal possibilities – without hum. The sculpted rear body contours are as beautiful as they are functional. This versatile, state-of-the-art instrument will inspire you to push your playing to new heights.Other features include sealed locking tuning machines, chrome hardware and bone nut. Includes premium molded hardshell case.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Jimmy Page Mirror Telecaster",
    img: "img/product05.jpg",
    price: 4699.0,
    company: "Fender",
    info: `When the opening riff of "Good Times Bad Times" came through the radio in 1969, everything changed. In that moment Jimmy Page cemented his legacy and altered the course of popular music with a single guitar: his Fender® Telecaster. The Fender Jimmy Page Mirror Telecaster is an homage to that guitar, which began life in its factory White Blonde lacquer finish, then became the "mirror guitar" before transforming into a one-of-a-kind hand-painted instrument. At each stage in its evolution, this legendary guitar produced some of the most iconic riffs of the 20th Century.
      The Jimmy Page Mirror Telecaster features a two-piece ash body, lacquer finish and a pair of Jimmy Page Custom '59 Tele® single-coil pickups that deliver the incendiary, full-bodied tone that inspired all the unforgettable licks on Led Zeppelin's first album. The custom "Oval C"-shaped maple neck has a 7.25"-radius slab rosewood fingerboard with 21 vintage-style frets, giving it a smooth playing feel. The "top-loader" bridge allows for through-body or top-load stringing, which produces a rounder, warmer tone and less tension so you can bend the strings with ease. Other features include a bone nut vintage-style round string tree and Pure Vintage Single Line "Fender Deluxe tuning machines for authentic style and performance.Created alongside Page himself, the Jimmy Page Telecaster also boasts some personalized touches like a Jimmy Page signature on the headstock and on the custom chrome neck plate. Included in the vintage tweed case are eight round mirrors (a tribute to the custom treatment Page later applied to the guitar), a black coiled cable, vintage-style "stained glass" strap and a custom Certificate of Authenticity. About his beloved Telecaster, Jimmy said it best: "I really made it my own – it’s quite a magical guitar."`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Buddy Guy Standard Stratocaster",
    img: "img/product06.jpg",
    price: 1899.0,
    company: "Fender",
    info:
      "Nail Buddy Guy's stinging tone and vibe on the dot with the Buddy Guy Standard Stratocaster. With a bold polka-dot finish as flamboyant as Guy himself, it's likely one of the most distinctive Strat® models you'll ever lay eyes (and hands) on. And with pure tone and vintage-style features, it's a superbly spot-on performer worthy of one of the greatest names in electric blues.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Jimi Hendrix Stratocaster",
    img: "img/product07.jpg",
    price: 1999.0,
    company: "Fender",
    info: `Honoring the electrifying "Voodoo Chile" who popularized the Stratocaster guitar and its tremendous sonic flexibility, the Jimi Hendrix Stratocaster gives you the same fiery tone and playing feel to wield as your own. Full of incendiary vintage tone and classic style, this extraordinary instrument features signature touches and unique appointments based on his distinctive "flipped-over" guitars.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Jim Root Stratocaster",
    img: "img/product08.jpg",
    price: 3899.0,
    company: "Fender",
    info: `For heavy, molten nu-metal Strat® style, the Jim Root Stratocaster delivers crushing detuned tone with a stark utilitarian look. The towering Slipknot guitarist joined us in creating a huge-sounding signature Strat model that complements his heavy playing style, and it's a monster—right down to its compound-radius fingerboard (12" to 16"), EMG® active humbucking pickups, sparse control layout and more. Brutal.`,
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 8,
  title: "Jim Root Stratocaster",
  img: "img/product04.jpg",
  price: 3899.0,
  company: "Fender",
  info: `For heavy, molten nu-metal Strat® style, the Jim Root Stratocaster delivers crushing detuned tone with a stark utilitarian look. The towering Slipknot guitarist joined us in creating a huge-sounding signature Strat model that complements his heavy playing style, and it's a monster—right down to its compound-radius fingerboard (12" to 16"), EMG® active humbucking pickups, sparse control layout and more. Brutal.`,
  inCart: false,
  count: 0,
  total: 0,
};
